[package]
name = "uploader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.3"
actix-files = "0.6.2"
actix-web = "4.4.0"
actix-web-error = "0.2.0"
actix-web-lab = "0.20.0"
askama = "0.12.1"
base64 = "0.21.5"
bytes = "1.5.0"
clap = { version = "4.4.7", features = ["derive"] }
futures = "0.3"
hmac = "0.12.1"
humantime = "2.1.0"
infer = "0.15.0"
mime = "0.3.16"
mime_guess = "2.0.4"
multer = "2.0.4"
once_cell = "1.15.0"
rand = "0.8.5"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
sha2 = "0.10.8"
thiserror = "1.0.50"
tokio = { version = "1.33", features = ["fs"] }
toml = "0.8.6"
tracing = "0.1.40"
tracing-actix-web = "0.7.8"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
