[package]
name = "uploader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4.9.0"
actix-web-error = "0.2.0"
actix-web-lab = "0.23.0"
askama = "0.12.1"
base64 = "0.22.1"
bytes = "1.7.2"
clap = { version = "4.5.20", features = ["derive"] }
futures = "0.3"
hmac = "0.12.1"
humantime = "2.1.0"
infer = "0.16.0"
mime = "0.3.16"
mime_guess = "2.0.5"
multer = "3.1.0"
once_cell = "1.20.2"
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
sha2 = "0.10.8"
thiserror = "1.0.64"
tokio = { version = "1.40", features = ["fs"] }
toml = "0.8.19"
tracing = "0.1.40"
tracing-actix-web = "0.7.14"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
