[package]
name = "uploader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.3"
actix-files = "0.6.2"
actix-web = "4.2.1"
actix-web-error = "0.1.0"
actix-web-lab = "0.18.5"
askama = "0.11.1"
base64 = "0.20.0"
bytes = "1.2.1"
futures = "0.3"
hmac = "0.12.1"
infer = "0.11.0"
mime = "0.3.16"
mime_guess = "2.0.4"
multer = "2.0.4"
once_cell = "1.15.0"
rand = "0.8.5"
serde = "1.0.145"
serde_json = "1.0.86"
sha2 = "0.10.6"
thiserror = "1.0.37"
tokio = { version = "1.21", features = ["fs"] }
toml = "0.5.9"
tracing = "0.1.37"
tracing-actix-web = "0.6.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
